#!/bin/bash

# Demo script showing Esnaad Code's continuous loop
# This demonstrates how the agent keeps running and accepting commands

echo "============================================"
echo "Esnaad Code - Continuous Loop Demonstration"
echo "============================================"
echo ""
echo "This script demonstrates how Esnaad Code works in a continuous loop."
echo ""
echo "Example session flow:"
echo ""
echo "1. User starts Esnaad Code"
echo "   $ esnaad"
echo ""
echo "2. Agent initializes and shows prompt"
echo "   esnaad> "
echo ""
echo "3. User asks first question"
echo "   esnaad> read package.json"
echo "   [Agent executes 'read' tool and shows response]"
echo ""
echo "4. Agent shows prompt again (LOOP CONTINUES)"
echo "   esnaad> "
echo ""
echo "5. User asks second question"
echo "   esnaad> create a new file hello.ts"
echo "   [Agent executes 'write' tool and shows response]"
echo ""
echo "6. Agent shows prompt again (LOOP CONTINUES)"
echo "   esnaad> "
echo ""
echo "7. User asks third question"
echo "   esnaad> find all typescript files"
echo "   [Agent executes 'glob' tool and shows response]"
echo ""
echo "8. Agent shows prompt again (LOOP CONTINUES)"
echo "   esnaad> "
echo ""
echo "9. This continues until user types /exit or presses Ctrl+D"
echo ""
echo "Key Features:"
echo "  ✓ Continuous loop - no need to restart after each command"
echo "  ✓ Context preserved - agent remembers previous conversation"
echo "  ✓ Multiple tools can be used in sequence"
echo "  ✓ Interactive commands (/help, /clear, /history)"
echo "  ✓ Graceful exit with /exit or Ctrl+D"
echo ""
echo "To try it yourself:"
echo "  1. Set OPENAI_API_KEY in .env file"
echo "  2. Run: npm start"
echo "  3. Start chatting with the agent"
echo "  4. Type multiple commands to see the loop in action"
echo ""
